### ISSUE TITLE
Make Argo templates version controlled

### ISSUE THREAD

**Issue by sytianhe** [argoproj/argo#148]
Spec Proposal: https://applatix.atlassian.net/wiki/spaces/ENG/pages/90374165/Make+Argo+templates+version+controlled

UI changes:

- [ ] Add commit selection step in the job creation wizard enhancement gui https://github.com/argoproj/argo/issues/264 
- [ ] Add template version selection option in the job creation wizard enhancement gui https://github.com/argoproj/argo/issues/263 
- [ ] Allow user to resubmit jobs with historical versions enhancement gui question https://github.com/argoproj/argo/issues/262 
- [ ] Display the historical template versions for the past jobs enhancement gui https://github.com/argoproj/argo/issues/261 
- [ ] Display the historical template versions that were used for the past versions of deployments enhancement gui https://github.com/argoproj/argo/issues/260 
- [ ] Display the service templates that are associated with each commit enhancement gui https://github.com/argoproj/argo/issues/259

**Comment by kxs-djackson** [comment]
why was this proposal abandoned?  seems like a useful feature
