### ISSUE TITLE
Epic: Create ArgoCli interface and refactor the Argo cli code to support k8s API and Argo API

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#1951]
I keep seeing this pattern of

```
if client.ArgoServer != "" {

} else {

}
```

This really tells me that we need an official Argo client which is interfaced and can switch between K8s API server vs. Argo API server, and abstracted away from the CLI.

# Tasks

* [x] archive/delete.go
* [x] archive/get.go
* [x] archive/list.go
