### ISSUE TITLE
What shall we back

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2606]
$ git log --oneline v2.7.0..master
* [ ] 51910292 (origin/master, master) chore: Lint UI on CI, test diagnostics, skip bad test (#2587)
* [ ] 232bb115 fix(error handling): use Errorf instead of New when throwing errors with formatted text (#2598)
* [ ] eeb2f97b fix(controller): dag continue on failed. Fixes #2596 (#2597)
* [ ] 99c35129 docs: Fix inaccurate field name in docs (#2591)
* [ ] 21c73779 fix: Fixes lint errors (#2594)
* [ ] 38aca5fa chore: Added ClusterWorkflowTemplate RBAC on quick-start manifests (#2576)
* [ ] 59f746e1 feat: UI enhancement for Cluster Workflow Template (#2525)
* [ ] 0801a428 fix(cli): Show lint errors of all files (#2552)
* [ ] c3535ba5 docs: Fix wrong Configuring Your Artifact Repository document. (#2586)
* [ ] 79217bc8 feat(archive): allow specifying a compression level (#2575)
* [ ] 88d261d7 fix: Use outputs of last child instead of retry node itslef (#2565)
* [ ] 5c08292e style: Correct the confused logic (#2577)
* [ ] 3d146144 fix: Fix bug in deleting pods. Fixes #2571 (#2572)
* [ ] cb739a68 feat: Cluster scoped workflow template (#2451)
* [ ] c63e3d40 feat: Show workflow duration in the index UI page (#2568)
* [ ] 1520452a chore: Error -> Warn when Parent CronWf no longer exists (#2566)
* [ ] ffbb3b89 fix: Fixes empty/missing CM. Fixes #2285 (#2562)
* [ ] d0fba6f4 chore: fix typos in the workflow template docs (#2563)
* [ ] 49801e32 chore(docker): upgrade base image for executor image (#2561)
* [ ] c4efb8f8 Add Riskified to the user list (#2558)
* [ ] 8b92d33e feat: Create K8S events on node completion. Closes #2274 (#2521)
* [ ] 2902e144 feat: Add node type and phase filter to UI (#2555)
* [ ] fb74ba1c fix: Separate global scope processing from local scope building (#2528)

**Comment by alexec** [comment]
@simster7 @sarabala1979 @whynowy once you'd added - please give me thumbs-up?

**Comment by simster7** [comment]
#2604 Should also be back-ported once it's merged
