### ISSUE TITLE
Cannot download artifacts from argo server ui (s3 repository artifact): The requested range is not satisfiable

### ISSUE THREAD

**Issue by lukaslentner** [argoproj/argo#3399]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I ran the https://argoproj.github.io/argo/examples/#artifacts example and cklciked on the generating pod in the argo ui. Then it takes some time and I get a white screen with "timed out waiting for the condition"

**What you expected to happen**:
To download the file

**How to reproduce it (as minimally and precisely as possible)**:
Run the exmple ...

**Anything else we need to know?**:
The file is definatly on S3 and can be downloaded there.
I use a local argo server to create the ui.
The file appears not as a download but a artifact43883929999be52fcf477caf2ac7531341ba31549.part.minio file is created in the folder I started the local argo server in. Although the file looks like just a part I can open it as if it were a tgz file and the content is complete.
So I guess the argo server wants to download the file first locally before offering it via UI to properly download in the browser. And this (first) internal download from S3 does not work.

**Environment**:

- Argo version:
`v2.9.1`
$ argo version
`v2.9.1`
- Kubernetes version :
`stable docker desktop windows version`
$ kubectl version -o yaml
`clientVersion:
  buildDate: "2019-10-15T12:11:03Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: windows/amd64
serverVersion:
  buildDate: "2019-10-15T12:02:12Z"
  compiler: gc
  gitCommit: 211047e9a1922595eaa3a1127ed365e9299a6c23
  gitTreeState: clean
  gitVersion: v1.14.8
  goVersion: go1.12.10
  major: "1"
  minor: "14"
  platform: linux/amd64`

**Logs**

S3 Load path: artifact438839299, key: namespace1/2020/07/07/artifact-passing-kfs44/artifact-passing-kfs44-623664270/hello-art.tgz
Creating minio client s3.amazonaws.com using static credentials
Getting from s3 (endpoint: s3.amazonaws.com, bucket: xxx-argo-artifact-repository, key: namespace1/2020/07/07/artifact-passing-kfs44/artifact-passing-kfs44-623664270/hello-art.tgz) to artifact438839299
Failed get file: The requested range is not satisfiable

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This is a another example where we should be streaming artefacts. See #3189

**Comment by alexec** [comment]
Can you please tell me how large the file is?

**Comment by lukaslentner** [comment]
Just like in the example some Kilobyte, nothing big ...

**Comment by lukaslentner** [comment]
Please do no close, as this is still interesting!

**Comment by alexec** [comment]
This could be fixed by streaming data. Would you like to submit a PR?
