### ISSUE TITLE
Cherry-pick for v2.12.0-rc6

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4748]
* [x] Saravanan Balasubramanian: fix(controller): Fixed workflow stuck with mutex lock 
* [ ] Alex Collins: feat(controller): Enhanced TTL controller scalability (#4736) (1a7ed7342)
* [x] Yuan Tang: fix(executor): Always check if resource has been deleted in checkResourceState() (#4738) (7437f4296)
* [x] Yuan Tang: fix(executor): Copy main/executor container resources from controller by value instead of reference (#4737) (122c5fd2e)
* [ ] Wylie Hobbs: docs: Update SSO docs to explain how to use the Argo CD Dex instance with Argo Workflows Server (#4729) (86fdd74a6)
* [x] Alex Collins: fix(ui): Fix YAML for workflows with storedWorkflowTemplateSpec. Fixes #4691 (#4695) (440d732d1)
* [x] Simon Behar: fix: Allow Bearer token in server mode (#4735) (ed853eb0e)
* [x] hermanhobnob: fix(executor): Deal with the pod watch API call timing out (#4734) (1f421df6b)
* [ ] Alex Collins: feat(controller): Pod deletion grace period. Fixes #4719 (#4725) (724fd80c4)
* [ ] bellevuerails: docs: minor typo fix (#4727) (c52cdd194)
* [ ] Alex Collins: feat(controller): Add Prometheus metric: `workflow_ttl_queue` (#4722) (380268943)
* [ ] Alex Collins: chore: Update stress test files. (#4721) (9f5c91028)
* [ ] Yuan Tang: fix(controller): Fix incorrect main container customization precedence and isResourcesSpecified check (#4681) (55019c6ea)
* [ ] Alex Collins: fix(ui): Fix "Using Your Login". Fixes #4707 (#4708) (625189d86)
* [ ] Alex Collins: feat(server): Support email for SSO+RBAC. Closes #4612 (#4644) (433dc5b99)
* [ ] Saravanan Balasubramanian: fix(controller): Fixed RBAC on leases (#4715) (ae0c0bb84)
* [ ] Saravanan Balasubramanian: fix(controller): Fixed Leader election name (#4709) (cd4adda1d)
* [ ] Saravanan Balasubramanian: fix(test): Fixed Flaky e2e tests TestSynchronizationWfLevelMutex and TestResourceTemplateStopAndTerminate/ResourceTemplateStop (#4688) (aec22189f)
* [ ] Saravanan Balasubramanian: fix(controller): Fix the RBAC for leader-election (#4706) (ab837753b)
* [x] Alex Collins: ci: Pin kustomize version (#4704) (1850b1f94)
* [ ] Jesse Suen: chore: direct users to ask questions on GitHub discussions (#4701) (06f514220)
* [x] Saravanan Balasubramanian: fix(controller): Increate default EventSpamBurst in Eventrecorder (#4698) (9669aa522)

**Comment by alexec** [comment]
I may want to cherry-pick 724fd80, but not today. It has at least one bug in it right now.

**Comment by alexec** [comment]
I have submitted my fixes.

**Comment by terrytangyuan** [comment]
Thanks. FYI, in order to cherry-pick #4681 and #4737, you would need #4656 as well.

**Comment by terrytangyuan** [comment]
Looks like rc6 has been released though it seems like #4737 is mentioned in release notes but the commit is not included.

**Comment by simster7** [comment]
I'll include them in GA
