### ISSUE TITLE
Cherry-pick for v2.12.0

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4764]
* [ ] Alex Collins: refactor(controller): Enhanced pod clean-up scalability (#4728) (69ce2acfb)
* [ ] Alex Collins: test: Improved e2e test robustness (#4758) (549585f16)
* [ ] Simon Behar: feat: Add a minimal prometheus server manifest (#4687) (9c4d735a9)
* [ ] Alex Collins: fix(ui): Remove unused Heebo files. Fixes #4730 (#4739) (625e3ce26)
* [x] Alex Collins: fix(controller): Fixes resource version misuse. Fixes #4714 (#4741) (2e278b011)
* [x] Alex Collins: fix(controller): Requeue when the pod was deleted. Fixes #4719 (#4742) (300db5e62)
* [X] Yuan Tang: fix(executor): Copy main/executor container resources from controller by value instead of reference (#4737) (122c5fd2e)
* [X] Yuan Tang: fix(controller): Fix incorrect main container customization precedence and isResourcesSpecified check (#4681) (55019c6ea)
* [X] Yuan Tang: feat(controller): Allow to configure main container resources (#4656) (b1e2c20)

**Comment by alexec** [comment]
`fix(controller): Requeue when the pod was deleted. Fixes #4719 (#4742) (300db5e)` only need to be cherry-picked if the original was already cherry-picked. You'll know if that's the case because the cherry-pick will conflict.

**Comment by alexec** [comment]
Done.

**Comment by simster7** [comment]
Released
