### ISSUE TITLE
Cherry pick for v2.12.3

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4826]
* [ ] Saravanan Balasubramanian: feat(controller): Adding Eventrecorder on LeaderElection (f037fd2b4)
* [x] Alex Collins: fix(controller): Various v2.12 fixes. Fixes #4798, #4801, #4806 (#4808) (a0024d0d4)
* [ ] kennytrytek: fix: Memoize Example (Issue 4626) (#4818) (ee59d49d9)
* [ ] Michael Albers: feat: Customize workfow metadata from event data (#4783) (b73bd2b61)
* [ ] Yuan Tang: chore: Remove redundant "from" in log message (#4813) (4eaae251d)
* [x] Kristoffer Johansson: fix: load all supported authentication plugins for k8s client-go (#4802) (7e6c799af)
* [ ] Alex Collins: fix(executor): Do not delete local artifacts after upload. Fixes #4676 (#4697) (78b0bffd3)
* [ ] Alex Collins: docs: Clarify PNS security (#4789) (764f118ca)
* [ ] Alex Collins: test: Fix TestDeletingRunningPod (#4779) (e86b377f4)
* [ ] dherman: refactor(ui): replace node-sass with sass (#4780) (af03a74fb)
* [ ] Yuan Tang: chore(example): Add watch timeout and print out workflow status message (#4740) (15ec9f5e4)
* [x] Alex Collins: fix(server): Do not silently ignore sso secret creation error (#4775) (4ac436d5c)
* [ ] RossyWhite: feat(controller): unix timestamp support on creationTimestamp var (#4763) (442d367b1)
* [x] Alex Collins: feat(controller): Rate-limit workflows. Closes #4718 (#4726) (9f67b28c7) **EXPECT CONFLICTS**
* [ ] Daisuke Taniwaki: Change argo-server crt/key owner (#4750) (aed25fefe)
* [x] Alex Collins: fix(controller): Support default database port. Fixes #4756 (#4757) (fbb4e8d44)
* [ ] Alex Collins: refactor(controller): Enhanced pod clean-up scalability (#4728) (69ce2acfb)
* [ ] Alex Collins: test: Improved e2e test robustness (#4758) (549585f16)
* [ ] Simon Behar: feat: Add a minimal prometheus server manifest (#4687) (9c4d735a9)
* [ ] Alex Collins: fix(ui): Remove unused Heebo files. Fixes #4730 (#4739) (625e3ce26)
* [x] 1a7ed7342312b658c501ee63ece8cb79d6792f88

**Comment by alexec** [comment]
a0024d0 will produce conflicts:

* For manifests/base/workflow-controller/workflow-controller-deployment.yaml, you want  `ports:` and `livenessProbe:`. We do not want `LEADER_ELECTION_IDENTITY`.
* For `Procfile` - we do not want `LEADER_ELECTION_IDENTITY`. 
* For the generated files,  run `make codegen` to fix them.

**Comment by simster7** [comment]
Release done
