### ISSUE TITLE
Cherry-pick for v2.12.4

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4863]
* [ ] Tomáš Coufal: feat: Expose exitCode to step level metrics (#4861) (f38c9a2d7)
* [ ] Alex Collins: feat(controller): `k8s_request_total` and `workflow_condition` metrics (#4811) (45c792a59)
* [x] Simon Behar: feat: Publish images on Quay.io (#4860) (e3320d360)
* [x] Simon Behar: feat: Publish images to Quay.io (#4854) (b674aa30b)
* [ ] J.P. Zivalich: refactor: upgrade kube client version to v0.19.6. Fixes #4425, #4791 (#4810) (a6301d7c6)
* [ ] Simon Behar: feat: Worker busy and active pod metrics (#4823) (6b3ce5045)
* [x] Song Juchao: fix: Preserve the original slice when removing string (#4835) (53110b61d)
* [x] cocotyty: fix(controller): keep special characters in json string when use withItems (#4814) (adfa988f9)
* [ ] Daisuke Taniwaki: feat(controller): Retry pod creation on API timeout (#4820) (6e158780e)
* [x] Alex Collins: build: Fix lint (#4837) (3c33ffb3f)
* [ ] Yuan Tang: chore: Bump OSS Go SDK to v2.1.5 (#4834) (945106e3d)
* [ ] Marcin Gucki: feat(controller): Add retry on different host (#4679) (01e6c9d5c)
* [ ] saranyaeu2987: fix: Metrics documentation (#4829) (2243d3497)
* [x] markterm: chore: add missing phase option to node cli command (#4825) (5f8a83a00)
* [ ] Trevor Wood: fix(crds): Inline WorkflowSteps schema to generate valid OpenAPI spec (#4828) (f0a315cf4)

**Comment by alexec** [comment]
I've marked 2 changes for inclusion.

**Comment by simster7** [comment]
Released
