### ISSUE TITLE
v2.12.5 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4904]
* [x] Saravanan Balasubramanian: fix: Mutex not being released on step completion (#4847) (929cd50e4)
* [ ] Alex Collins: fix(ui): UI bug fixes (#4895) (c1f9280a2)
* [ ] Yuan Tang: feat: Support specifying the pattern for transient and retryable errors (#4889) (25abd1a03)
* [ ] Alex Collins: build: on a dev branch automatically start the UI (#4896) (0c5ebbba4)
* [ ] Alex Collins: Revert "feat(cli): add selector and field-selector option to the stop command. (#4853)" (16f25ba09)
* [ ] Noah Hanjun Lee: feat(cli): add selector and field-selector option to the stop command. (#4853) (53f7998eb)
* [ ] Isaac Gaskin: fix(workflow-event-bindings): removing unneeded ':' in protocol (#4893) (1f13241fe)
* [ ] Alex Collins: fix(ui): Show non-pod nodes (#4890) (ecbca6ce7)
* [x] Simon Behar: fix(controller): Consider processed retry node in metrics. Fixes #4846 (#4872) (4a5db1b79)
* [ ] BOOK: feat(controller): optional database migration (#4869) (dd8c1ba02)
* [ ] Alex Collins: feat(ui): Argo Events API and UI. Fixes #888 (#4470) (a8e934826)
* [x] ermeaney: fix(controller): make creator label DNS compliant. Fixes #4880 (#4881) (17e79e8a2)
* [x] lonsdale8734: fix(controller): Fix node status when daemon pod deleted but its children nodes are still running (#4683) (2ff11cc98)
* [x] Simon Behar: fix: Do not error on duplicate workflow creation by cron (#4871) (955a4bb12)
* [ ] Alex Collins: build: sudoless `make codegen -B` (#4866) (239272a10)
* [ ] Alex Collins: fix(controller): Add matrix tests for node offload disabled. Resolves #2333 (#4864) (622624e81)
* [ ] Tomáš Coufal: feat: Expose exitCode to step level metrics (#4861) (f38c9a2d7)

**Comment by alexec** [comment]
Just one fix from me.

I think we should exclude #4861 unless there is a pressing reason? It's a feature, not a fix.

**Comment by simster7** [comment]
> I think we should exclude #4861 unless there is a pressing reason? It's a feature, not a fix.

Sure

**Comment by simster7** [comment]
Released
