### ISSUE TITLE
v2.12.6 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4945]
* [ ] nishant-d: docs: add Devtron labs to USERS.md (#4939) 2254ac905
* [ ] Alex Collins: fix(ui): v3 UI tweaks (#4933) 9d4edaef4
* [ ] Alex Collins: build: Faster `make start`, faster smoke jobs (#4926) 8f2f42760
* [ ] tczhao: fix(ui): fix object-editor text render issue (#4921) 2d73d58a5
* [ ] BOOK: feat: support K8S json patch (#4908) 6e961ec92
* [ ] Alex Collins: chore: Introduce `WorkflowPhase` (#4856) 957ef677c
* [ ] Alex Collins: fix(controller): Report reconciliation errors better (#4877) f872366f3
* [ ] Alex Collins: feat(controller)!: Key-only artifacts. Fixes #3184 (#4618) c8215f972
* [ ] tczhao: fix(ui): objecteditor only runs onChange when values are modified (#4911) cd7c16b23
* [ ] Alex Collins: build: Inline Argo Events CRD URLs to reduce build errors (#4902) 8c353d949
* [ ] Alex Collins: fix(ui): Fix workflow refresh bug (#4906) ee1f82764
* [x] Saravanan Balasubramanian: fix: Mutex not being released on step completion (#4847) 929cd50e4
* [ ] Alex Collins: fix(ui): UI bug fixes (#4895) c1f9280a2
* [ ] Yuan Tang: feat: Support specifying the pattern for transient and retryable errors (#4889) 25abd1a03
* [ ] Alex Collins: build: on a dev branch automatically start the UI (#4896) 0c5ebbba4
* [ ] Alex Collins: Revert "feat(cli): add selector and field-selector option to the stop command. (#4853)" 16f25ba09
* [ ] Noah Hanjun Lee: feat(cli): add selector and field-selector option to the stop command. (#4853) 53f7998eb
* [ ] Isaac Gaskin: fix(workflow-event-bindings): removing unneeded ':' in protocol (#4893) 1f13241fe
* [x] Alex Collins: feat(server): Support email for SSO+RBAC. Closes #4612 (#4644) 433dc5b99

**Comment by alexec** [comment]
Done. Nothing to add.

**Comment by simster7** [comment]
Released
