### ISSUE TITLE
v2.12.7 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4986]
* [ ] Simon Behar: fix: Use button in side panel links (#4977) d324b43c7
* [ ] Alex Collins: docs: Fix broken docs (#4967) 2672a933b
* [ ] Alex Collins: fix: Surface the underlying error on wait timeout. (#4966) 655c7e253
* [ ] Alex Collins: fix: Correct usage of wait.ExponentialBackoff (#4962) a00aa3257
* [ ] Simon Behar: docs: Specify states to ensure clean state when releaseing (#4963) faa3363f7
* [ ] Alex Collins: docs: Update running-locally.md (#4961) 64147238b
* [ ] Alex Collins: fix(server): Fix missing logs bug (#4960) e00623d61
* [ ] Alex Collins: ci: Run all executors on CI (#4957) 1d8b9549f
* [ ] tczhao: feat(server): add ServiceAccount info to api/v1/userinfo and ui user tab (#4944) eabe96376
* [ ] Simeon H.K. Fitch: Added Astraea (#4855) 15156d193
* [ ] tczhao: fix(controller): report OOM when wait container OOM (#4930) 7404b1f8a
* [x] Yuan Tang: feat: Support retry on transient errors during executor status checking (#4946) 6166e80c5
* [ ] Maximilian Roos: docs: Remove miscreant line in argo.md (#4821) f06550d71
* [ ] Alex Collins: docs: Update security docs (#4743) 727e27a92
* [x] Simon Behar: chore: Remove self-referential replace directive in go.mod (#4959) b6efd00cd
* [ ] kennytrytek: docs: Improve Documents Around Inputs (#4900) 2ebcb9f99
* [ ] Alex Collins: feat(crds): Update CRDs to apiextensions.k8s.io/v1 (#4918) 6e116e46e
* [ ] Alex Collins: feat(server): Add Prometheus metrics. Closes #4751 (#4952) 261625324
* [x] Simon Behar: chore: Set Go mod to /v2 (#4916) 0bffade33
* [ ] Simon Behar: fix(cli): Allow full node name in node-field-selector (#4913) 7c69898ed
* [ ] Alex Collins: fix(cli): Update the map-reduce example, fix bug. (#4948) c7293062a
* [ ] Saravanan Balasubramanian: feat: Check the workflow is not being deleted for Synchronization workflow (#4935) e7e51d08a
* [ ] nishant-d: docs: add Devtron labs to USERS.md (#4939) 2254ac905
* [ ] Alex Collins: fix(ui): v3 UI tweaks (#4933) 9d4edaef4
* [ ] Alex Collins: build: Faster `make start`, faster smoke jobs (#4926) 8f2f42760
* [ ] tczhao: fix(ui): fix object-editor text render issue (#4921) 2d73d58a5
* [ ] BOOK: feat: support K8S json patch (#4908) 6e961ec92
* [ ] Alex Collins: chore: Introduce `WorkflowPhase` (#4856) 957ef677c
* [ ] Alex Collins: fix(controller): Report reconciliation errors better (#4877) f872366f3
* [ ] Alex Collins: feat(controller)!: Key-only artifacts. Fixes #3184 (#4618) c8215f972
* [ ] tczhao: fix(ui): objecteditor only runs onChange when values are modified (#4911) cd7c16b23
* [ ] Alex Collins: build: Inline Argo Events CRD URLs to reduce build errors (#4902) 8c353d949

**Comment by alexec** [comment]
Can we please add the metrics commit?

**Comment by alexec** [comment]
Also, once this is done. We should move immediately to v3.0.0-rc1

**Comment by simster7** [comment]
> Can we please add the metrics commit?

@alexec To claify: you mean #4952 right?

> Also, once this is done. We should move immediately to v3.0.0-rc1

Fully agree

**Comment by alexec** [comment]
Correct.

**Comment by simster7** [comment]
Released
