### ISSUE TITLE
v2.12.8 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#5048]
* [x] Alex Collins: fix(cli): Add insecure-skip-verify for HTTP1. Fixes #5008 (#5015) 425173a28
* [ ] Yuan Tang: chore: Reuse LookupEnvDurationOr to parse duration from environment variables (#5032) 3edb55c19
* [ ] Alastair Maw: M is demonstrably not less than 1 in the examples (#5021) 48b669cca
* [ ] tczhao: feat(controller): configurable terminationGracePeriodSeconds (#4940) 5915a2164
* [ ] Stéphane Este-Gracias: Fix golang build (#5039) 5824fc6bb
* [ ] Simon Behar: feat: DAG render options panel float through scrolling (#5036) ef76f729a
* [x] Saravanan Balasubramanian: fix: Skip the Workflow not found error in Concurrency policy (#5030) b4ea47e05
* [ ] Alex Collins: fix(ui): Display all node inputs/output in one tab. Resolves #5027 (#5029) edbe5bc9e
* [ ] Alex Collins: feat(executor): Log `verb kind statusCode` for executor Kubernetes API requests (#4989) c4e8d1cf2
* [x] Simon Behar: fix: Unmark daemoned nodes after stopping them (#5005) d1abcb055
* [ ] Viktor Farcic: Video (#5019) 38e98f7ee
* [ ] Huan-Cheng Chang: docs: Add a note for docker executors regarding outputs.result (#5017) d40c117c0
* [ ] Alex Collins: fix(ui): Fix event-flow hidden nodes (#5013) 342caeff5
* [ ] Alex Collins: build: Upgrade Golang to v1.15 (#5009) 1b77ec80e
* [ ] Alex Collins: build: Upgrade argoexec base image to debian:10.7-slim (#5010) c232d2376
* [ ] Alex Collins: feat(executor): Upgrade kubectl to v1.19 (#5011) d5ccc8e01
* [ ] Alex Collins: test: Delete TestDeletingRunningPod (#5012) d3b7adb1f
* [ ] joyciep: feat: Set CORS headers (#4990) 8f5e17ac4
* [ ] Huan-Cheng Chang: feat(ui): Node search tool in UI Workflow viewer (#5000) 99c049bd2
* [ ] Huan-Cheng Chang: fix: Fail DAG templates with variables with invalid dependencies (#4992) 5047f0738
* [ ] Simon Behar: chore: Set Go mod to v3 (#4978) a730b4f43
* [ ] Simon Behar: fix: Coalesce UI filtering menus (#4972) ccd669e44
* [ ] Yuan Tang: docs: Add Couler, SQLFlow, and Kubeflow to USERS.md (#4964) 7710a2cac
* [ ] Yuan Tang: feat: Configurable retry backoff settings when retrying API calls (#4979) ce508c896
* [ ] Alex Collins: test: Fix TestDeletingRunningPod (#4996) 61e8b9637
* [ ] Arthur Outhenin-Chalandre: fix(controller): Revert prepending ExecutorScriptSourcePath which brought a breaking change in args handling (#4884) 44a4f7e10
* [ ] Alex Collins: fix(controller): Adds PNS_PRIVILEGED, fixed termination bug (#4983) b68d63eb2
* [ ] Simon Behar: fix: Use button in side panel links (#4977) d324b43c7
* [ ] Alex Collins: docs: Fix broken docs (#4967) 2672a933b
* [ ] Alex Collins: fix: Surface the underlying error on wait timeout. (#4966) 655c7e253
* [ ] Alex Collins: fix: Correct usage of wait.ExponentialBackoff (#4962) a00aa3257
* [ ] Simon Behar: docs: Specify states to ensure clean state when releaseing (#4963) faa3363f7
* [ ] Alex Collins: docs: Update running-locally.md (#4961) 64147238b
* [ ] Alex Collins: fix(server): Fix missing logs bug (#4960) e00623d61
* [ ] Alex Collins: ci: Run all executors on CI (#4957) 1d8b9549f
* [ ] tczhao: feat(server): add ServiceAccount info to api/v1/userinfo and ui user tab (#4944) eabe96376
* [ ] Simeon H.K. Fitch: Added Astraea (#4855) 15156d193
* [ ] tczhao: fix(controller): report OOM when wait container OOM (#4930) 7404b1f8a

**Comment by simster7** [comment]
Released
